# -*- coding: utf-8 -*-
"""RPT prac 10 B3 I066 Srihari Thyagarajan 29th September.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUBkDWScWifejsGWQrCtNcLF3ivZuld8

RPT prac 10 B3 I066 Srihari Thyagarajan 29th September
"""

# Import libraries
import numpy as np
from sympy import symbols, solve
import pandas as pd
import scipy.stats as stats

"""Q.1 A sample size of 5 results in the sample values 9, 7, 1, 4, and 6.

a. What is the sample mean?
"""

a1=9
a2=7
a3=1
a4=4
a5=6
l = [a1, a2, a3, a4, a5]
mean = np.mean(l)
print("The mean of the given list input is : ", mean)

"""b. What is the sample variance?"""

var = np.var(l)
print("The Sample variance of the given list input is : ", var)

"""Unbiased estimate of sample variance is

$\hat{S}^{2}=\frac{n}{n-1} S^{2}$

c. What is the unbiased estimate of the sample variance?

Q. 2. The true mean of a quiz conducted in a class of 50 students is 70 points, and
the true standard deviation is 12 points. Estimate the mean by sampling a
subset of the scores, without replacement.

${\sigma^{2}_{\overline{X}}}=\frac{\sigma^{2}_{X}}{n}(\frac{N-n}{N-1})$

a. What is the standard deviation of the sample mean if only 10 scores are
used?
"""

N = 50
n = 10
true_standard_dev = 12
sd = ((true_standard_dev**2)/n)*((N-n)/(N-1))
sd**(1/2)

"""b. How large should the sample size be for the standard deviation of the
sample mean to be 1% of the true mean?
"""

# True mean = 70
# 1% of 70 = 0.7

k = symbols('k')
expr = (((144/k) * ((50-k)/49)) ** (1/2)-0.7)
sol = solve(expr)
sol

"""Q.3. A random sample of size 81 is taken from a population that has a mean of 24 

and variance 324. Use the central limit theorem to determine the probability that the sample mean lies between 23.9 and 24.2.
"""

N = 81
me = 24
vr = 324
# P(23.9<x<24.2)
z1 = (23.9-24)/(18/9)
z2 = (24.2-24)/(18/9)
z1,z2

stats.zscore([z1,z2])

"""Q.4. A random number generator produces three-digit random numbers that
are uniformly distributed between 0.000 and 0.999.

a. If the generator produces the sequence of numbers 0.276, 0.123, 0.072,
0.324, 0.815, 0.312, 0.432, 0.283, and 0.717, what is the sample mean?
Aashray ans. 0.372
"""

a = (0.276, 0.123, 0.072, 0.324, 0.815, 0.312, 0.432, 0.283, 0.717)
lw = 0
for i in a:
  lw += i
lw = lw/ (len(a))
print(lw)

"""b. What is the variance of the sample mean of numbers produced by the
random number generator?

"""

var = 0
for i in a:
  var += (i - lw) ** 2
var /= len(a)
print(var)

"""c. How large should the sample size be in order to obtain a sample mean
whose standard deviation is no greater than 0.01?
"""

E = .37
Z_alpha = 0.05
sigma = 0.1
n = 90
Sample_size = (Z_alpha * E **2)/sigma * n
Sample_size

# End of practical session.